name: machine_test_app
description: Flutter Machine Test App - generated example
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true